// import { Plugin } from 'vite';
// import { parseHtml } from './html-parse-precompile';

// interface HtmlPrecompileOptions {
//   /** 是否生成源码映射，默认为true */
//   sourceMap?: boolean;
// }

// /**
//  * Vite插件：HTML预编译为AST
//  * 
//  * 功能特性：
//  * 1. 在构建时将HTML模板预编译为AST对象
//  * 2. 减少运行时解析开销，提升性能
//  * 3. 支持源码映射，便于调试
//  * 4. 可自定义转换逻辑
//  */
// function htmlPrecompilePlugin(options: HtmlPrecompileOptions = {}): Plugin {
//   const {
//     sourceMap = true,
//   } = options;

//   return {
//     name: 'solely-html-precompile',

//     // 插件应用顺序
//     enforce: 'pre',

//     /**
//      * 转换HTML文件为AST
//      */
//     transform(code: string, id: string) {
//       // 检查是否为HTML文件
//       if (!id.endsWith('.html?solely')) {
//         return null;
//       }

//       try {
//         // 解析HTML为AST
//         const ast = parseHtml(code);
//         const newId = id.split('?')[0];
//         // 生成转换后的代码
//         let transformedCode = `
// // Auto-generated by solely-html-precompile plugin
// // Source: ${newId}

// ${ast}
// `.trim();

//         // 构建结果
//         const result: any = {
//           code: transformedCode,
//           map: sourceMap ? {
//             version: 3,
//             file: newId,
//             sourceRoot: '',
//             // 确保 sources 指向原始文件路径 (newId)
//             sources: [newId],
//             sourcesContent: [code],
//             names: [],
//             // 简单插件通常只映射到文件的开始
//             // 可以使用如 'source-map' 库来生成更精确的映射，
//             // 但对于 AST 转换，简单映射到整个文件通常就足够了。
//             // Mappings: AACA,QAAO,CAAC,CAAC (示例：映射第一行)
//             mappings: 'AAAA'
//           } : null,
//           hasDefaultExport: true
//         };

//         return result;

//       } catch (error) {
//         const errorMessage = `[solely-html-precompile] Error processing ${id}: ${error instanceof Error ? error.message : String(error)}`;
//         console.error(errorMessage);
//         // 使用 Vite 的错误抛出机制，能更好地在 Dev Server 中展示
//         this.error({
//           message: errorMessage,
//           id: id,
//           frame: code // 附带源码片段
//         });
//       }
//     },

//     /**
//      * 处理热更新
//      */
//     handleHotUpdate({ file, server }) {
//       if (file.endsWith('.html?solely')) {
//         server.ws.send({
//           type: 'full-reload',
//           path: '*'
//         });
//       }
//     }
//   };
// }


// // ==================== 以下 3 行是「终极防 tree-shake」必杀技 ====================
// // 缺一不可，所有知名插件（unplugin、vite-plugin-vue 等）都偷偷用了类似写法

// export default htmlPrecompilePlugin;